### ISSUE TITLE
Can't wait to try your model

### ISSUE THREAD

**Issue by hyfu0583** [Boese0601/MagicDance#1]
Great job!
Would you guys consider releasing your code and pretrained model?

**Comment by Geliv** [comment]
+1

**Comment by LcenArthas** [comment]
+1

**Comment by Boese0601** [comment]
Thanks for your interest in our work😘

I’m currently cleaning up the code since the project contains some internal package from Bytedance which may cause license issues. As soon as I finish this, all pretrained weights and code will be released, estimated around the end of December. 

Thanks for your patience.
