### ISSUE TITLE
RuntimeError: shape '[13, 77, 8, 40]' is invalid for input of size 788480

### ISSUE THREAD

**Issue by Jeff-Fudan** [Boese0601/MagicDance#12]
When I train the appearance_control_pretraining using the TikTok data you provided with a batch size of 32, I encounter a RuntimeError: shape '[13, 77, 8, 40]' is invalid for input of size 788480. In reality, 788480=[32,77,8,40]. However, when I set the batch size to 1, everything works fine. The paper mentions a batch size of 64 for the first stage, is this an issue with the code or the data?.Thank you once again for your excellent work! It does a great job of preserving the human id.

**Comment by Boese0601** [comment]
Hi, I didn't come across such a problem with my end when I trained the model with train_batch_size=8 on each of the  8 GPUs (64 in total). Can you please retry with train_batch_size=8 and see if the problem exists? 

This problem may caused by the dataloader and the data because I used internal data structure and data-loading packages from ByteDance for training rather than pytorch dataloader.

**Comment by Boese0601** [comment]
Hi, I have solved the problem and updated the dataloader and training script. You should be able to use any value for batch_size now. Thanks.

**Comment by Jeff-Fudan** [comment]
Thank you so much！
